### ISSUE TITLE
want to use specific permission

### ISSUE THREAD

**Issue by appglobaltech** [dpa99c/cordova-diagnostic-plugin-android-runtime-example#1]
I want to use specific permission at runtime...the code which is provided gives almost all the permissions....
can you please help ?

**Comment by dpa99c** [comment]
This project serves an as example of how to use [cordova-diagnostic-plugin](https://github.com/dpa99c/cordova-diagnostic-plugin#requestruntimepermission) and hence illustrates how all runtime permissions can be requested.

If you only need to request a single permission, then see the [plugin documention for `requestRuntimePermission()`](https://github.com/dpa99c/cordova-diagnostic-plugin#requestruntimepermission), passing the desired [runtime permission constant](https://github.com/dpa99c/cordova-diagnostic-plugin#dangerous-runtime-permissions) to it.
