### ISSUE TITLE
Not sure how to request a single particular permission.

### ISSUE THREAD

**Issue by ParaSpl01t** [dpa99c/cordova-diagnostic-plugin-android-runtime-example#2]
I've checked the sample apk and glad this plugin is working. but how can one request only single permission. suppose READ_EXTERNAL_STORAGE or WRITE_EXTERNAL_STORAGE.

**Comment by dpa99c** [comment]
[requestRuntimePermission()](https://github.com/dpa99c/cordova-diagnostic-plugin#requestruntimepermission)
